### ISSUE TITLE
bug: 我照官方配置demo 和 code 块没有显示出来

### ISSUE THREAD

**Issue by InfernalAzazel** [BuptStEve/vuepress-plugin-demo-code#48] opened 2022-09-26 03:39 UTC
vite: "^3.1.0",
    vue: "^3.2.39",
    vuepress: "2.0.0-beta.51",
    vuepress-plugin-demo-code: "2.0.0-beta.1"

![Screenshot from 2022-09-26 11-34-36](https://user-images.githubusercontent.com/40333954/192189121-cc05eb07-b15c-4388-a275-7dcf40d58729.png)
![Screenshot from 2022-09-26 11-38-22](https://user-images.githubusercontent.com/40333954/192189230-22ee09bb-df43-4685-9bfa-0d8f110e675d.png)

**Comment by BuptStEve** [comment] 2022-10-10 07:16
有可能因为 vuepress 又更新了导致不匹配了，我回头看看

**Comment by BuptStEve** [comment] 2022-10-17 02:14
应该是因为 beta.50 版本开始只支持 esm 导致的...
https://github.com/vuepress/vuepress-next/pull/1030

**Comment by BuptStEve** [comment] 2023-04-14 06:09
Closing as duplicate of #51

**Closed as completed by BuptStEve** 2023-04-14 06:09 UTC
Labels: bug
